# Writing Style Prompt for SlackerNews Documentation

## Detailed Style Guide

When writing in the style of the SlackerNews documentation author, follow these key principles:

**Tone & Voice:**
- Use a direct, professional but approachable tone
- Be concise and practical - focus on actionable information
- Maintain confidence without being overly casual
- Write for technical audiences who appreciate clarity over marketing speak

**Structure & Organization:**
- Lead with clear, descriptive headings using standard markdown hierarchy
- Use numbered lists for sequential steps and bullet points for options/features
- Include code blocks with proper syntax highlighting for commands and configurations
- Organize information in logical, scannable chunks

**Language Patterns:**
- Use active voice predominantly ("Install the Preflight plugin" not "The Preflight plugin should be installed")
- Employ imperative mood for instructions ("Run the command" rather than "You should run the command")
- Keep sentences relatively short and declarative
- Use technical terminology accurately without over-explaining basics
- Include specific version numbers, exact commands, and precise configuration details

**Content Approach:**
- Prioritize practical implementation over theory
- Provide context for why steps are necessary, but briefly
- Include troubleshooting guidance and alternative approaches
- Reference related sections with clear links
- Use consistent formatting for similar types of information (commands, file paths, URLs)

## Five Excellent Style Examples from the Text

### Example 1:
> "SlackerNews requires TLS certificates signed by a trusted certificate authority for Slack to connect securely to your instance. You should supply the certificates as a base64 encoded string."

This demonstrates the author's direct, technical approach with clear reasoning and specific implementation details.

### Example 2:
> "The CLI will tell you where the archive is saved. If the built-in analyzers don't solve your problem, please contact us and send the support bundle archive for our team to look at."

Shows the practical, helpful tone with clear next steps and escalation path.

### Example 3:
> "For demo mode installations, you can install without providing any of the values below, unless you need to access the images from your own registry."

Exhibits the author's skill at providing conditional guidance clearly and concisely.

### Example 4:
> "We recommend Ubuntu 20.04, but also support the following operating systems:"

Demonstrates the pattern of leading with recommendations while providing comprehensive alternatives.

### Example 5:
> "Install the Preflight `kubectl` plugin and run our Preflight Checks:"

Perfect example of the imperative mood with specific technical details in backticks.

## Five Generated Paragraphs That DON'T Match the Style

### Poor Example 1:
> "Hey there! So you're probably wondering how to get SlackerNews up and running, right? Well, you've come to the right place! We're going to walk through this together, step by step, and don't worry if you're not super technical - we'll explain everything in detail as we go!"

**Why it doesn't fit:** Too casual and conversational, uses unnecessary filler words, talks down to the audience, and lacks the direct, professional tone of the original.

### Poor Example 2:
> "The installation process involves several methodologies that can be implemented depending on your organizational requirements and infrastructure preferences. Various stakeholders should be consulted to determine the optimal deployment strategy that aligns with your enterprise architecture paradigms."

**Why it doesn't fit:** Overly verbose and corporate, uses buzzwords without substance, lacks concrete actionable information, and doesn't match the practical, direct approach.

### Poor Example 3:
> "You might want to think about installing SlackerNews, though there are many considerations you should probably take into account. Perhaps you could try using Helm, or maybe the VM option would be better for your use case, but it really depends on what you're trying to accomplish."

**Why it doesn't fit:** Too tentative and wishy-washy, lacks the confident, decisive tone, doesn't provide clear guidance, and uses hedge words excessively.

### Poor Example 4:
> "WARNING! CRITICAL! You absolutely MUST follow these steps exactly or your installation WILL fail catastrophically! Do NOT deviate from these instructions under ANY circumstances! Failure to comply may result in complete system failure!"

**Why it doesn't fit:** Overly dramatic and alarmist, uses excessive capitalization and exclamation points, creates unnecessary anxiety rather than the calm, confident guidance of the original.

### Poor Example 5:
> "Installing stuff can be tricky, but here's how you do it. First, get some things ready. Then, run some commands. Make sure everything works. If not, try again or ask someone for help."

**Why it doesn't fit:** Too vague and lacks specificity, uses informal language ("stuff," "things"), doesn't provide the detailed technical information expected, and lacks the professional precision of the original documentation.
