sendkeys_timeout: 0
session: mbta
root: /home/crdant/workspace/mbta-mcp-server
windows:
- name: zsh
  panes:
  - commands: 
    - claude
  layout: tiled
- name: nvim
  root: /home/crdant/workspace/mbta-mcp-server
  commands:
    - nvim

