sendkeys_timeout: 0
session: window
windows:
- name: zsh
  root: /home/crdant/workspace/clusters
  panes:
  - commands: []
  layout: tiled
- name: nvim
  root: /home/crdant/workspace/clusters
  commands:
    - nvim

