# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" "usbhid" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    # ext4 filesystem inside the cryptroot LUKS mapping (see nixos.nix)
    # REPLACE after reinstall: UUID of the inner filesystem, from
    # nixos-generate-config or blkid /dev/mapper/cryptroot
    { device = "/dev/disk/by-uuid/REPLACE-WITH-INNER-FS-UUID";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EDAC-1406";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ] ;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}

