# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" "usbhid" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    # nixos-generate-config or blkid /dev/mapper/cryptroot
    { device = "/dev/mapper/cryptroot";
      fsType = "brtfs";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/2d3429b5-e164-4d4c-b502-cffda278a6ff"

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3D93-1F15";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ] ;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}

