model: gpt-4o

prompt: > 
  Ask me one question at a time so we can develop a thorough,
  step-by-step spec for this idea. Each question should build on my previous
  answers, and our end goal is to have a detailed specification I can hand off to
  a developer. Let’s do this iteratively and dig into every relevant detail.
  Remember, only one question at a time.

  Once we are done, save the spec as spec.md

  Here’s the idea: $input

options:
  temperature: 0.6
  top_p: 0.9
  frequency_penalty: 0.5
  presence_penalty: 0.4
