#!/usr/bin/env bash

mkdir -p ${HOME}/.dotfiles.bak
os="$(uname | awk '{print tolower($1)}')"

if [ -n "${MY_DIR}" ] ; then
  DOTFILES=${HOME}/.dotfiles
else
  SELFPATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELFPATH=${SELFPATH}/$(basename -- "$0")
  SELFDIR=`dirname ${SELFPATH}`
  DOTFILES=`dirname ${SELFDIR}`
fi

# make sure the SSH config directory exists with appropriate permissions
if [ ! -d ${HOME}/.ssh ] ; then
    mkdir ${HOME}/.ssh
fi
chmod 700 ${HOME}/.ssh

# setup various dotfiles
DATESTAMP=$(date +%Y%m%dT%H%M%S)
if [[ -f ${HOME}/.ackrc  ]] ; then
  mv ${HOME}/.ackrc ${HOME}/.dotfiles.bak/ackrc.${DATESTAMP}
fi
ln -sf ${DOTFILES}/ackrc ${HOME}/.ackrc

if [[ -f ${HOME}/.curlrc  ]] ; then
  mv ${HOME}/.curlrc ${HOME}/.dotfiles.bak/curlrc.${DATESTAMP}
fi
ln -sf ${DOTFILES}/curlrc ${HOME}/.curlrc

if [[ -f ${HOME}/.editorconfig  ]] ; then
  mv ${HOME}/.editorconfig ${HOME}/.dotfiles.bak/editorconfig.${DATESTAMP}
fi
ln -sf ${DOTFILES}/editorconfig ${HOME}/.editorconfig

if [[ -f ${HOME}/.emacs  ]] ; then
  mv ${HOME}/.emacs ${HOME}/.dotfiles.bak/emacs.${DATESTAMP}
fi
ln -sf ${DOTFILES}/emacs ${HOME}/.emacs

if [[ -d ${HOME}/.config/nvim ]] ; then
  mv ${HOME}/.config/nvim ${HOME}/.dotfiles.bak/nvim.${DATESTAMP}
fi
ln -sf ${DOTFILES}/nvim ${HOME}/.config/nvim

if [[ -f ${HOME}/.ssh/config  ]] ; then
  mv ${HOME}/.ssh/config ${HOME}/.dotfiles.bak/ssh-config.${DATESTAMP}
fi
ln -sf ${DOTFILES}/ssh/config ${HOME}/.ssh/config

if [[ -f ${HOME}/.gitconfig  ]] ; then
  mv ${HOME}/.gitconfig ${HOME}/.dotfiles.bak/gitconfig.${DATESTAMP}
fi
ln -sf ${DOTFILES}/gitconfig.${os} ${HOME}/.gitconfig

if [[ -f ${HOME}/.packerconfig  ]] ; then
  mv ${HOME}/.packerconfig ${HOME}/.dotfiles.bak/packerconfig.${DATESTAMP}
fi
ln -sf ${DOTFILES}/packerconfig ${HOME}/.packerconfig

if [[ -f ${HOME}/.zshrc  ]] ; then
  mv ${HOME}/.zshrc ${HOME}/.dotfiles.bak/zshrc.${DATESTAMP}
fi
ln -sf ${DOTFILES}/zshrc ${HOME}/.zshrc

if [[ -f ${HOME}/.zshenv  ]] ; then
  mv ${HOME}/.zshenv ${HOME}/.dotfiles.bak/zshenv.${DATESTAMP}
fi
ln -sf ${DOTFILES}/zshenv ${HOME}/.zshenv

# confirm SSH with my keys will be allowed
cat ${DOTFILES}/ssh/*.pub >> ${HOME}/.ssh/authorized_keys
chmod 600 ${HOME}/.ssh/authorized_keys

if [[ ! -d ${HOME}/.config/ ]]; then
  mkdir ${HOME}/.config
fi

if [[ os == "darwin"  ]]; then
  # add Bartender configuration
  cp ${HOME}/Library/Preferences/com.surteesstudios.Bartender.plist ${HOME}/.dotfiles.bak/com.surteesstudios.Bartender.plist.${DATESTAMP}
  ln -sf ${DOTFILES}/Library/Preferences/com.surteesstudios.Bartender.plist ${HOME}/Library/Preferences/com.surteesstudios.Bartender.plist

  # add brand color palettes
  cp ${HOME}/Library/Colors/*.clr ${HOME}/.dotfiles.bak
  ln -sf ${DOTFILES}/Library/Colors/*.clr ${HOME}/Library/Colors
  
  if [[ -d ${HOME}/.config/karabiner ]]; then
    mv ${HOME}/.config ~/.dotfiles.bak/karabiner.${DATESTAMP}
  fi
  ln -sf ${DOTFILES}/karabiner ${HOME}/.config/karabiner
fi

if which espanso 2>&1 1>/dev/null; then
  cp -r "$(espanso path config)" ${HOME}/.dotfiles.bak/espanso.${DATESTAMP}
  ln -sf ${DOTFILES}/espanso "$(espanso path config)"
fi

# add aws configuration
if [[ -d ${HOME}/.aws  ]] ; then
  mv ${HOME}/.aws ${HOME}/.dotfiles.bak/aws.${DATESTAMP}
fi
ln -sf ${DOTFILES}/aws ${HOME}/.aws

# link in tmux configuration
if [[ -d ${HOME}/.tmux ]]; then
  mv ${HOME}/.tmux ~/.dotfiles.bak/tmux.${DATESTAMP}
fi
ln -sf ${DOTFILES}/tmux ${HOME}/.tmux

if [[ -d ${HOME}/.tmux ]]; then
  mv ${HOME}/.tmux.conf ~/.dotfiles.bak/tmux.conf.${DATESTAMP}
fi
ln -sf ${DOTFILES}/tmux.conf ${HOME}/.tmux.conf

# link in cargo configuration
if [[ -d ${HOME}/.cargo  ]] ; then
  mkdir ${HOME}/.dotfiles.bak/cargo.${DATESTAMP}
  mv ${HOME}/.cargo/config.cson ${HOME}/.dotfiles.bak/cargo/
else
  mkdir ${HOME}/.cargo
fi

# gnupg
if [[ -d ${HOME}/.gnupg  ]] ; then
  mkdir ${HOME}/.dotfiles.bak/gnupg.${DATESTAMP}
  mv ${HOME}/.gnupg/*.conf ${HOME}/.dotfiles.bak/gnupg/
else
  mkdir ${HOME}/.gnupg
fi
ln -s ${HOME}/.dotfiles/gnupg/*.conf ~/.gnupg

ln -sf ${DOTFILES}/vimrc.local ${HOME}/.vimrc.local
