#!/usr/bin/env bash

# default to zsh for my user
sudo chsh -s /bin/zsh ${USER}

# import Github's GPG keys
curl https://github.com/web-flow.gpg | gpg --import

# import my GPG keys
curl https://github.com/crdant.gpg | gpg --import

# convert color palette links to hard links so that the palettes
# load correctly in the color picker
find ${HOME}/Library/Colors -type l -exec bash -c 'ln -f "$(greadlink -m "$0")" "$0"' {} \;1

# use the same mechanism for preference files
find ${HOME}/Library/Preferences -name "*.plist" -a -type l -exec bash -c 'ln -f "$(greadlink -m "$0")" "$0"' {} \;1

# Install useful extensions for VSCode"
code --install-extension EditorConfig.EditorConfig --force 
code --install-extension esbenp.prettier-vscode --force
code --install-extension file-icons.file-icons --force
code --install-extension jaspernorth.vscode-pigments --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vsliveshare.vsliveshare --force
code --install-extension ms-vsliveshare.vsliveshare-audio --force
code --install-extension ms-vsliveshare.vsliveshare-pack --force
code --install-extension coenraads.bracket-pair-colorizer-2 --force
code --install-extension britesnow.vscode-toggle-quotes --force
code --install-extension vscodevim.vim --force
code --install-extension Gruntfuggly.todo-tree --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension redhat.vscode-yaml --force
code --install-extension GitHub.vscode-pull-request-github --force
code --install-extension Pivotal.vscode-concourse --force

# install Dockutil from the Github release
dockutil_url=$(curl -s https://api.github.com/repos/kcrawford/dockutil/releases/latest | jq -r '.assets[].browser_download_url')
dockutil_installer=/tmp/$(curl -s https://api.github.com/repos/kcrawford/dockutil/releases/latest | jq -r '.assets[].name')
curl -o ${dockutil_installer} ${dockutil_url} && chmod 755 ${dockutil_installer}
sudo installer -pkg ${dockutil_installer} -target /

# set up Dock
dockutil --remove all
dockutil --add "/Applications/iTerm.app"
dockutil --add "/Applications/Google Chrome.app" --after "iTerm"
dockutil --add "/Applications/Slack.app" --after "Google Chrome"
dockutil --add "/Applications/Superhuman.app" --after "Slack"
dockutil --add "/System/Applications/Messages.app" --after "Superhuman"
dockutil --add "/Applications/Twitter.app" --after "Messages"
dockutil --add "/System/Applications/Contacts.app" --after "Twitter"
dockutil --add "/Applications/Fantastical.app" --after "Contacts"
dockutil --add "/Applications/Todoist.app" --after "Fantastical"
dockutil --add "/Applications/Bear.app" --after "Todoist"
dockutil --add "/System/Applications/News.app" --after "Bear"
dockutil --add "/System/Applications/Music.app" --after "News"
dockutil --add "/System/Applications/TV.app" --after "Music"
dockutil --add "/System/Applications/Books.app" --after "TV"
dockutil --add "/System/Applications/Photos.app" --after "Books"
dockutil --add "/Applications/Keynote.app" --after "Photos"
dockutil --add "/Applications/Numbers.app" --after "Keynote"
dockutil --add "/Applications/Pages.app" --after "Numbers"
dockutil --add "/Applications/Visual Studio Code.app" --after "Pages"
dockutil --add "/Applications/Postman.app" --after "Visual Studio Code"
dockutil --add "/System/Applications/App Store.app" --after "Postman"
dockutil --add "/System/Applications/Utilities/Activity Monitor.app" --after "App Store"
dockutil --add "/System/Applications/Utilities/Console.app" --after "Activity Monitor"
dockutil --add "/System/Applications/System Preferences.app" --after "Console"

# setup some directories
mkdir -p ~/sandbox
mkdir -p ~/workspace
mkdir -p ~/workspace/learning
mkdir -p ~/workspace/learning/exercism
mkdir -p ~/"Virtual Box VMs"

# setup aliases I'm used to having
SetFile -a C ~/workspace

# follow the LSB for some home-level content
mkdir -p ~/bin
mkdir -p ~/share

# Common file folders and links
mkdir -p ~/Documents/Inbox 
ln -sf ~/Documents/Inbox ~/Desktop
mkdir -p ~/Documents/Outbox 
ln -sf ~/Documents/Outbox ~/Desktop
mkdir -p ~/Documents/Archive 
ln -sf ~/Documents/Archive ~/Desktop
mkdir -p ~/Documents/Pending 
ln -sf ~/Documents/Pending ~/Desktop
mkdir -p ~/Documents/Projects 
ln -sf ~/Documents/Projects ~/Desktop
mkdir -p ~/Documents/Read 
ln -sf ~/Documents/Read ~/Desktop
mkdir -p ~/Documents/Watch 
ln -sf ~/Documents/Watch ~/Desktop

# setup login items
loginitems -a  "Alfred 4"
open /Applications/Alfred\ 4.app

loginitems -a "Bartender 4"
open "/Applications/Bartender 4.app"

loginitems -a "Espanso"
open /Applications/Espanso.app

loginitems -a "Popclip"
open /Applications/Popclip.app

loginitems -a "Todoist"
open /Applications/Todoist.app

loginitems -a "Amphetamine"
open /Applications/Amphetamine.app

loginitems -a "Tailscale"
open /Applications/Tailscale.app
